apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: weather-app
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: weather-app
          image: mohammadmahmoud/weather-app
