apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  labels:
    app: weather-app-frontend
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: weather-app-frontend

    spec:
      containers:
        - name: weather-app-frontend
          image: mohammadmahmoud/weather-app-frontend

  replicas: 3
  selector:
    matchLabels:
      app: weather-app-frontend
